# — your existing settings —
baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hello World"
theme = "PolyRhythmic"

# — new settings —

[permalinks]
  projects = "/projects/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 10

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/"
    weight     = 20

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/#contact"
    weight     = 30
