# — your existing settings —
buildFuture = true
baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hello World"
theme = "hello-friend-ng"

[permalinks]
  projects = "/projects/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 10

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/"
    weight     = 20

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/#contact"
    weight     = 30



[params]
  customCSS = [
    "css/custom.css",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css",
  ]
  customJS  = [
    "js/contact.js",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js",
  ]

