# — your existing settings —
buildFuture = true
baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hello World"
theme = "hello-friend-ng"

[permalinks]
  projects = "/projects/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 10

  [[menu.main]]
    identifier = "myself"
    name       = "Myself"
    url        = "/myself/"
    weight     = 15

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/"
    weight     = 20

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/#contact"
    weight     = 30



[params]
  customCSS = ["css/custom.css"]
  customJS  = ["js/contact.js"]

